use strict;
use warnings;

use Test::More tests => 12;
use Test::MockObject::Extends;
use Test::Exception;

use DateTime;
use XML::LibXML;

use File::Slurp;

use_ok('wtsi_clarity::epp::reports::manifest');

local $ENV{'WTSI_CLARITY_HOME'} = q[t/data/config];

my $EXPECTED_FILE_CONTENT = [
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ccb79679-2400-11e5-9fe5-8c82b12cf1e3',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample97',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ccb79679-2400-11e5-9fe5-8c82b12cf1e3'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c38d453e-2400-11e5-9fe5-d0d05948628e',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample98',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c38d453e-2400-11e5-9fe5-d0d05948628e'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c296a8e8-2400-11e5-9fe5-cdbafcab50e7',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample99',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c296a8e8-2400-11e5-9fe5-cdbafcab50e7'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c31072c1-2400-11e5-9fe5-f3a4e17d05d2',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample100',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c31072c1-2400-11e5-9fe5-f3a4e17d05d2'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'cd4f58be-2400-11e5-9fe5-a97430dc4661',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample101',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'cd4f58be-2400-11e5-9fe5-a97430dc4661'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c8d6fd97-2400-11e5-9fe5-e5bab0b224a2',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample102',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c8d6fd97-2400-11e5-9fe5-e5bab0b224a2'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c85624d4-2400-11e5-9fe5-9cff681f631b',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample103',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c85624d4-2400-11e5-9fe5-9cff681f631b'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c7e0e336-2400-11e5-9fe5-d4eb9d21f255',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample104',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:1',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c7e0e336-2400-11e5-9fe5-d4eb9d21f255'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c7696da4-2400-11e5-9fe5-ed03e459712b',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample105',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c7696da4-2400-11e5-9fe5-ed03e459712b'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'cc0803fd-2400-11e5-9fe5-dc92320f1c5b',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample106',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'cc0803fd-2400-11e5-9fe5-dc92320f1c5b'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ca5af566-2400-11e5-9fe5-9a725efa0b63',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample107',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ca5af566-2400-11e5-9fe5-9a725efa0b63'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c9e41553-2400-11e5-9fe5-d46e58db14b6',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample108',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c9e41553-2400-11e5-9fe5-d46e58db14b6'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c95b44df-2400-11e5-9fe5-86f5e8a9a387',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample109',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c95b44df-2400-11e5-9fe5-86f5e8a9a387'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c404fa35-2400-11e5-9fe5-d6e5b2903d79',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample110',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c404fa35-2400-11e5-9fe5-d6e5b2903d79'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c4a08441-2400-11e5-9fe5-938a4867e38a',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample111',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c4a08441-2400-11e5-9fe5-938a4867e38a'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'cdfe3cfa-2400-11e5-9fe5-fcff8c824031',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample112',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:2',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'cdfe3cfa-2400-11e5-9fe5-fcff8c824031'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ce9cfda4-2400-11e5-9fe5-bb8bdc189ebc',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample113',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ce9cfda4-2400-11e5-9fe5-bb8bdc189ebc'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c651d822-2400-11e5-9fe5-a9ed59c4ad42',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample114',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c651d822-2400-11e5-9fe5-a9ed59c4ad42'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c6ec2cba-2400-11e5-9fe5-a5167eb58136',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample115',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c6ec2cba-2400-11e5-9fe5-a5167eb58136'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c52b949b-2400-11e5-9fe5-b106cf309542',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample116',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c52b949b-2400-11e5-9fe5-b106cf309542'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c5b603c0-2400-11e5-9fe5-d94181b87978',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample117',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c5b603c0-2400-11e5-9fe5-d94181b87978'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd15b6c4a-2400-11e5-9fe5-8481658f97ff',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample118',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd15b6c4a-2400-11e5-9fe5-8481658f97ff'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd1e1d97f-2400-11e5-9fe5-b6555de3fa63',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample119',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd1e1d97f-2400-11e5-9fe5-b6555de3fa63'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd27b0e02-2400-11e5-9fe5-d695a02434aa',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample120',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:3',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd27b0e02-2400-11e5-9fe5-d695a02434aa'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd3c46182-2400-11e5-9fe5-8c2086aa0cd5',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample121',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd3c46182-2400-11e5-9fe5-8c2086aa0cd5'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'cf2e3b3e-2400-11e5-9fe5-b083a8f212cf',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample122',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'cf2e3b3e-2400-11e5-9fe5-b083a8f212cf'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'cfbe3747-2400-11e5-9fe5-934e8d1a37f6',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample123',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'cfbe3747-2400-11e5-9fe5-934e8d1a37f6'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd0479c49-2400-11e5-9fe5-edcc2e84fbd9',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample124',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd0479c49-2400-11e5-9fe5-edcc2e84fbd9'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd0cc52c8-2400-11e5-9fe5-aabeaea0c56a',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample125',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd0cc52c8-2400-11e5-9fe5-aabeaea0c56a'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd7af219c-2400-11e5-9fe5-a16037dc47af',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample126',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd7af219c-2400-11e5-9fe5-a16037dc47af'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd8489623-2400-11e5-9fe5-ac330803b93f',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample127',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd8489623-2400-11e5-9fe5-ac330803b93f'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd7142ae6-2400-11e5-9fe5-c4d07ff39567',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample128',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:4',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd7142ae6-2400-11e5-9fe5-c4d07ff39567'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd67c36fb-2400-11e5-9fe5-bbfada1fa395',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample129',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd67c36fb-2400-11e5-9fe5-bbfada1fa395'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd5f662dd-2400-11e5-9fe5-f092e4363885',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample130',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd5f662dd-2400-11e5-9fe5-f092e4363885'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd56901f9-2400-11e5-9fe5-d9e4f1febe51',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample131',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd56901f9-2400-11e5-9fe5-d9e4f1febe51'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd4e27874-2400-11e5-9fe5-d92ca1761766',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample132',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd4e27874-2400-11e5-9fe5-d92ca1761766'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd44ebb8e-2400-11e5-9fe5-e1c5d8f08404',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample133',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd44ebb8e-2400-11e5-9fe5-e1c5d8f08404'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'dc7b0901-2400-11e5-9fe5-8e68ef013051',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample134',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'dc7b0901-2400-11e5-9fe5-8e68ef013051'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'dd321821-2400-11e5-9fe5-a43024822bef',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample135',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'dd321821-2400-11e5-9fe5-a43024822bef'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'db2bd9f8-2400-11e5-9fe5-bfb9371d4a2f',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample136',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:5',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'db2bd9f8-2400-11e5-9fe5-bfb9371d4a2f'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'dbc70e83-2400-11e5-9fe5-955ec793fa0c',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample137',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'dbc70e83-2400-11e5-9fe5-955ec793fa0c'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'da1201bf-2400-11e5-9fe5-d32e4cb0a2f3',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample138',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'da1201bf-2400-11e5-9fe5-d32e4cb0a2f3'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'da975710-2400-11e5-9fe5-9411cfa5793a',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample139',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'da975710-2400-11e5-9fe5-9411cfa5793a'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd8f779e5-2400-11e5-9fe5-86672d6e89d8',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample140',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd8f779e5-2400-11e5-9fe5-86672d6e89d8'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'd995ed10-2400-11e5-9fe5-837bc0baed71',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample141',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'd995ed10-2400-11e5-9fe5-837bc0baed71'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e2488a94-2400-11e5-9fe5-d0c6d4bef843',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample142',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e2488a94-2400-11e5-9fe5-d0c6d4bef843'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e2d72932-2400-11e5-9fe5-bd18fc8ae625',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample143',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e2d72932-2400-11e5-9fe5-bd18fc8ae625'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e0b7552a-2400-11e5-9fe5-c18771fcceca',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample144',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:6',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e0b7552a-2400-11e5-9fe5-c18771fcceca'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e0314836-2400-11e5-9fe5-f8999c9d7d53',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample145',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e0314836-2400-11e5-9fe5-f8999c9d7d53'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'df768154-2400-11e5-9fe5-acdaf2adfd4d',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample146',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'df768154-2400-11e5-9fe5-acdaf2adfd4d'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'dee86310-2400-11e5-9fe5-faa66a568bac',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample147',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'dee86310-2400-11e5-9fe5-faa66a568bac'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'de5983d4-2400-11e5-9fe5-dd2f7249dd34',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample148',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'de5983d4-2400-11e5-9fe5-dd2f7249dd34'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ddbec32e-2400-11e5-9fe5-c8651015ea65',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample149',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ddbec32e-2400-11e5-9fe5-c8651015ea65'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e6ce6f48-2400-11e5-9fe5-e655cee8cf85',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample150',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e6ce6f48-2400-11e5-9fe5-e655cee8cf85'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e760ab06-2400-11e5-9fe5-db3bfc1bc881',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample151',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e760ab06-2400-11e5-9fe5-db3bfc1bc881'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e35eb492-2400-11e5-9fe5-a1c812cc7a7e',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample152',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:7',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e35eb492-2400-11e5-9fe5-a1c812cc7a7e'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e3dfbde5-2400-11e5-9fe5-c6c93361d056',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample153',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e3dfbde5-2400-11e5-9fe5-c6c93361d056'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e468238d-2400-11e5-9fe5-acbb7ab4bbbf',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample154',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e468238d-2400-11e5-9fe5-acbb7ab4bbbf'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e4e9b169-2400-11e5-9fe5-85b8f897e1a8',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample155',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e4e9b169-2400-11e5-9fe5-85b8f897e1a8'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e13ea0e7-2400-11e5-9fe5-d39b2e5d6003',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample156',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e13ea0e7-2400-11e5-9fe5-d39b2e5d6003'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e1c4e9b2-2400-11e5-9fe5-f952dd84ce55',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample157',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e1c4e9b2-2400-11e5-9fe5-f952dd84ce55'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c01c5234-2400-11e5-9fe5-e87847af0734',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample158',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c01c5234-2400-11e5-9fe5-e87847af0734'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c190717c-2400-11e5-9fe5-f349b7744c9c',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample159',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c190717c-2400-11e5-9fe5-f349b7744c9c'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c2108e0c-2400-11e5-9fe5-a9eaf1451d96',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample160',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:8',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c2108e0c-2400-11e5-9fe5-a9eaf1451d96'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c098490c-2400-11e5-9fe5-925a59d408ae',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample161',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c098490c-2400-11e5-9fe5-925a59d408ae'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'c1122b96-2400-11e5-9fe5-c47c8f02f120',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample162',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'c1122b96-2400-11e5-9fe5-c47c8f02f120'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'bd13884f-2400-11e5-9fe5-8d3fdb7b1905',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample163',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'bd13884f-2400-11e5-9fe5-8d3fdb7b1905'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'bd963546-2400-11e5-9fe5-ef7e1508a196',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample164',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'bd963546-2400-11e5-9fe5-ef7e1508a196'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'bc208c04-2400-11e5-9fe5-f47b737f8f79',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample165',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'bc208c04-2400-11e5-9fe5-f47b737f8f79'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'bc9849ec-2400-11e5-9fe5-baeceb86fee9',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample166',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'bc9849ec-2400-11e5-9fe5-baeceb86fee9'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'bf1047f5-2400-11e5-9fe5-bb646897fb34',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample167',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'bf1047f5-2400-11e5-9fe5-bb646897fb34'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'bf9442c2-2400-11e5-9fe5-cdbb57c680e8',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample168',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:9',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'bf9442c2-2400-11e5-9fe5-cdbb57c680e8'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'be1745f2-2400-11e5-9fe5-e6aa6d6f9197',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample169',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'be1745f2-2400-11e5-9fe5-e6aa6d6f9197'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'be86a58c-2400-11e5-9fe5-d7c32020dcd8',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample170',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'be86a58c-2400-11e5-9fe5-d7c32020dcd8'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'f033efd6-2400-11e5-9fe5-a90bf2bb34cd',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample171',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'f033efd6-2400-11e5-9fe5-a90bf2bb34cd'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'efc42246-2400-11e5-9fe5-e912c7b6a2f7',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample172',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'efc42246-2400-11e5-9fe5-e912c7b6a2f7'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'f10988a7-2400-11e5-9fe5-cc5fbad915e0',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample173',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'f10988a7-2400-11e5-9fe5-cc5fbad915e0'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ee48e922-2400-11e5-9fe5-8f06f806757a',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample174',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ee48e922-2400-11e5-9fe5-8f06f806757a'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'f09a1ce8-2400-11e5-9fe5-88ef151038e2',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample175',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'f09a1ce8-2400-11e5-9fe5-88ef151038e2'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ef5acfa8-2400-11e5-9fe5-dd6c9b4f54f0',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample176',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:10',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ef5acfa8-2400-11e5-9fe5-dd6c9b4f54f0'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'edd7645c-2400-11e5-9fe5-dec8dfe3ba4a',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample177',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'edd7645c-2400-11e5-9fe5-dec8dfe3ba4a'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ec8196c2-2400-11e5-9fe5-e541cd149f92',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample178',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ec8196c2-2400-11e5-9fe5-e541cd149f92'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'eec4fcf8-2400-11e5-9fe5-c55b85db1763',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample179',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'eec4fcf8-2400-11e5-9fe5-c55b85db1763'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ed5fe698-2400-11e5-9fe5-ef9a84ee668a',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample180',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ed5fe698-2400-11e5-9fe5-ef9a84ee668a'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ec10688a-2400-11e5-9fe5-895a93ff4a23',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample181',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ec10688a-2400-11e5-9fe5-895a93ff4a23'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ead8ff4a-2400-11e5-9fe5-ae8d3230cd26',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample182',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ead8ff4a-2400-11e5-9fe5-ae8d3230cd26'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'eced734c-2400-11e5-9fe5-be0d7bfbb786',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample183',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'eced734c-2400-11e5-9fe5-be0d7bfbb786'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ebab5c2d-2400-11e5-9fe5-de2db733ecf1',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample184',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:11',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ebab5c2d-2400-11e5-9fe5-de2db733ecf1'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'ea6a2a66-2400-11e5-9fe5-967f95ba36d1',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample185',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'A:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'ea6a2a66-2400-11e5-9fe5-967f95ba36d1'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e7f7bff9-2400-11e5-9fe5-d48a379c1b5f',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample186',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'B:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e7f7bff9-2400-11e5-9fe5-d48a379c1b5f'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'eb433b76-2400-11e5-9fe5-cf5bcecca726',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample187',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'C:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'eb433b76-2400-11e5-9fe5-cf5bcecca726'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e93288aa-2400-11e5-9fe5-a5c20d61d5cd',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample188',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'D:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e93288aa-2400-11e5-9fe5-a5c20d61d5cd'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e892c823-2400-11e5-9fe5-bf8c7f90c6bc',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample189',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'E:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e892c823-2400-11e5-9fe5-bf8c7f90c6bc'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e590f9a0-2400-11e5-9fe5-d74125770b64',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample190',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'F:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e590f9a0-2400-11e5-9fe5-d74125770b64'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '9606',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e63abb40-2400-11e5-9fe5-d7bbe8c49e64',
    'UDF/WTSI Organism' => 'Homo Sapiens',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample191',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'G:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e63abb40-2400-11e5-9fe5-d7bbe8c49e64'
  },
  {
    'UDF/WTSI Supplier Volume' => '',
    'UDF/WTSI Taxon ID' => '',
    'Project Name' => 'UTF-8 TEST Project',
    'UDF/WTSI Bait Library Name' => 'Human all exon V5',
    'Sample UUID' => 'e9c3afba-2400-11e5-9fe5-f624b8a99bf8',
    'UDF/WTSI Organism' => '',
    'UDF/WTSI Requested Size Range From' => '',
    'Sample/Name' => 'sample192',
    'UDF/WTSI Supplier' => '',
    'UDF/WTSI Phenotype' => '',
    'UDF/WTSI Requested Size Range To' => '',
    'Container/Name' => '5262710738856',
    'Sample/Well Location' => 'H:12',
    'Project ID' => 'ERD851',
    'UDF/WTSI Supplier Gender - (SM)' => 'Male',
    'Container/Type' => 'ABgene 0800',
    'UDF/WTSI Donor ID' => 'e9c3afba-2400-11e5-9fe5-f624b8a99bf8'
  }
];

{
  local $ENV{'WTSICLARITY_WEBCACHE_DIR'} = 't/data/epp/generic/manifest';

  my $manifest = wtsi_clarity::epp::reports::manifest->new(
    process_url => 'http://clarity.com/processes/1',
  );

  my $containers_xml = XML::LibXML->load_xml(
    location => $ENV{'WTSICLARITY_WEBCACHE_DIR'} . '/POST/containers.batch_a96e03cdcd0c7bb75d2263d8cdf143b0'
  );

  my $container = $containers_xml->findnodes('/con:details/con:container')->pop();

  my $file_content = $manifest->file_content($container);
  $file_content = $manifest->_sort_file_content($file_content, $manifest->sort_order, $manifest->sort_by_column);

  is_deeply($file_content, $EXPECTED_FILE_CONTENT, 'File content is generated from a container node correctly');

  is($manifest->publish_to_irods, 1, "Return correctly the publish to external iRODS setting");

  my $publish_reports_to_irods_called;
  my $mocked_manifest = Test::MockObject::Extends->new(
    wtsi_clarity::epp::reports::manifest->new(
      process_url => 'http://clarity.com/processes/1',
      save_file   => 1,
    )
  );
  $mocked_manifest->mock(q{now}, sub {
    return "20150813121212";
  });
  $mocked_manifest->mock(q{publish_to_irods}, sub {
    return 1;
  });
  $mocked_manifest->mock(q{_publish_report_to_irods}, sub {
    ++$publish_reports_to_irods_called;
    return 1;
  });
  $mocked_manifest->mock(q{md5_hash}, sub {
    return '12345';
  });
  $mocked_manifest->mock(q{insert_hash_to_database}, sub {
    return 1;
  });

  my $saveas_called = 0;
  my $mocked_file = Test::MockObject::Extends->new(
    $mocked_manifest->_file_factory->create(
      type      => 'report_writer',
      headers   => $mocked_manifest->headers,
      data      => $file_content,
      delimiter => $mocked_manifest->file_delimiter,
    )
  );
  $mocked_file->mock(q{saveas}, sub {
    return ++$saveas_called;
  });

  $mocked_manifest->_output_file($mocked_file, "test_file.txt");

  is($publish_reports_to_irods_called, 1, '_publish_report_to_irods function called');
  is($saveas_called, 2, 'Successfully called the saveas method.');
  my $expected_file_name = "27-11037.20150813121212.manifest.txt";

  is($mocked_manifest->file_name($container), $expected_file_name, 'Creates a file name correctly');
}

{
  local $ENV{'WTSICLARITY_WEBCACHE_DIR'} = 't/data/epp/generic/manifest';

  my $manifest = wtsi_clarity::epp::reports::manifest->new(
    process_url => 'http://clarity.com/processes/1',
  );

  my $containers_xml = XML::LibXML->load_xml(
    location => $ENV{'WTSICLARITY_WEBCACHE_DIR'} . '/POST/containers.batch_a96e03cdcd0c7bb75d2263d8cdf143b0'
  );

  my $container = $containers_xml->findnodes('/con:details/con:container')->pop();

  my $file_content = $manifest->file_content($container);
  $file_content = $manifest->_sort_file_content($file_content, $manifest->sort_order, $manifest->sort_by_column);

  is_deeply($file_content, $EXPECTED_FILE_CONTENT,
    'File content is generated from a container node correctly');

  is($manifest->publish_to_irods, 1, "Return correctly the publish to external iRODS setting");

  my $publish_reports_to_irods_called;
  my $mocked_manifest = Test::MockObject::Extends->new(
    wtsi_clarity::epp::reports::manifest->new(
      process_url => 'http://clarity.com/processes/1',
    )
  );
  $mocked_manifest->mock(q{now}, sub {
    return "20150813121212";
  });
  $mocked_manifest->mock(q{publish_to_irods}, sub {
    return 1;
  });
  $mocked_manifest->mock(q{_publish_report_to_irods}, sub {
    ++$publish_reports_to_irods_called;
    return 1;
  });

  my $saveas_called;
  my $mocked_file = Test::MockObject::Extends->new(
    $mocked_manifest->_file_factory->create(
      type      => 'report_writer',
      headers   => $mocked_manifest->headers,
      data      => $file_content,
      delimiter => $mocked_manifest->file_delimiter,
    )
  );
  $mocked_file->mock(q{saveas}, sub {
    ++$saveas_called;
  });

  $mocked_manifest->_output_file($mocked_file, "test_file.txt");

  is($publish_reports_to_irods_called, 1, '_publish_report_to_irods function called');
  is($saveas_called, 1, 'Successfully called the saveas method.');
  my $expected_file_name = "27-11037.20150813121212.manifest.txt";

  is($mocked_manifest->file_name($container), $expected_file_name, 'Creates a file name correctly');
}

{
  local $ENV{'WTSICLARITY_WEBCACHE_DIR'} = 't/data/epp/generic/manifest';

  my $manifest = Test::MockObject::Extends->new(
    wtsi_clarity::epp::reports::manifest->new(
      process_url       => 'http://clarity.com/processes/1',
      publish_to_irods  => 1
    )
  )->mock(q(_irods_publisher), sub {
    return Test::MockObject->new()->mock(q(publish), sub {
    });
  });

  my $report_path = $ENV{'WTSICLARITY_WEBCACHE_DIR'} . q{/example_manifest.txt};

  lives_ok {
    $manifest->_publish_report_to_irods($report_path)
  } 'Successfully published the file into iRODS.';
}

1;