#!/bin/bash
#
# A project version number generator for git repositories. This script will
# report a version number taken from annotated git tags, using `git describe'.
#
# Version: 0.0.1
#
# Author: kdj@sanger.ac.uk
#
# Taken from https://github.com/wtsi-npg/pb_calibration/blob/devel/bin/gitver

function usage {
    echo "Generate a version number using git describe."
    echo "Options:"
    echo " -a Use any ref found in .git/refs/, instead of using only"
    echo " the annotated tags."
    echo " -c Abort if there are uncommitted changes."
    echo " -h Display this help."
    echo " -t Abort if there are untracked files."
}

GIT=git

uncommitted_tag=-dirty
committed_only=no
tracked_only=no

git_args="--always"

set -- $(getopt cht "$@")

while [ $# -gt 0 ]
do
case "$1" in
        (-a) git_args="$git_args --all";;
        (-c) committed_only=yes;;
        (-h) usage; exit 0;;
        (-t) tracked_only=yes;;
        (--) shift; break;;
        (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
        (*) break;;
    esac
shift
done

if [ -n "$($GIT status --porcelain --untracked-files=no)" ]; then
if [ $committed_only == "yes" ]; then
echo -n >&2 "Cannot make a version number; "
        echo >&2 "there uncommitted changes in your checkout."
        exit 1;
    else
git_args="$git_args --dirty=$uncommitted_tag"
    fi
fi


if [ -n "$($GIT status --porcelain --untracked-files=normal) | grep -E '^\\?\\?'" ]; then
if [ $tracked_only == "yes" ]; then
echo -n >&2 "Cannot make a version number; "
        echo >&2 "there are untracked files in your checkout."
        exit 1;
    fi
fi

git describe $git_args

